### ISSUE TITLE
Does not recognise console.log()

### ISSUE THREAD

**Issue by whenmoon** [pierregoutheraud/atom-js-console#8]
<img width="401" alt="screen shot 2019-02-01 at 17 57 22" src="https://user-images.githubusercontent.com/33122888/52137465-e43ab980-264a-11e9-8ac6-d5fce601c1c6.png">

**Comment by TomWestrope** [comment]
I am also getting this same issue

**Comment by hvquy001** [comment]
Go to Packages / Atom Js Console -> View Code -> Open lib/Editor.js find `sandbox` variable and replace by that:
`const sandbox = { window, ...window, console: {
        log: function(str){
          stdout.push(str);
        }
      } }`

**Comment by jrvieira** [comment]
It's an environmental API, not part of JS itself. You can be working within an environment that doesn't implement it. Even if we assume the environment, its return value should be undefined.
